POSTGRES:
    Password: abcdef
IAM_ROOT: rootatIAM
AuthZ:
    Server: 
        Url: http://192.168.1.66:9096
        Endpoints:
            UserSignUp: /user-signup
            Login: /login
    
Client:
    Url: http://192.168.1.66:9094
    